#!/usr/bin/env bash
while read oldrev newrev ref
do
  echo "Ref $ref successfully received.  Deploying to next.cottagelabs.com..."
  git --work-tree=/var/www/next.cottagelabs.com --git-dir=/home/cloo/next.cottagelabs.com.git checkout -f $ref
  sudo nginx -t && sudo nginx -s reload
done
